#!/usr/bin/with-contenv bash

# Usage: /sbin/slapd-backup dbnum filename
dbnum=$1
filename=$2

backupPath="/data/backup"

# delete backups that are over $BACKUP_TTL days
find $backupPath -type f -mtime +$BACKUP_TTL -exec rm {} \;

# Date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"
backupFilePath="$backupPath/$(date "$dateFileFormat")-$filename.gz"

/usr/sbin/slapcat -F /etc/ldap/slapd.d -n $dbnum | gzip > $backupFilePath
chmod 600 $backupFilePath

exit 0
