#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/09-nginx ]; then

	### Check to see if this is a new install, if yes create directories...
	if [ ! -f /www/html/index.html ] ; then
	   echo "** [nginx] No Files found - Creating Blank File"
	   mkdir -p /www/html
	   touch /www/html/index.html
	   chown nginx /www/html
	fi

	### Force Reset Permissions for Security
    	chown -R nginx /www/html

        mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/09-nginx
fi

echo ''
echo '** [nginx] Starting nginx..'
exec nginx

