#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="nginx"
check_container_initialized
check_service_initialized init

if [ ! -f /www/html/index.html ] ; then
   print_notice "No Files found - Creating Blank index.html"
   mkdir -p /www/html
   touch /www/html/index.html
   chown nginx /www/html
fi

liftoff

print_info "Starting nginx"
exec nginx
