#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service 10-openldap
PROCESS_NAME="nginx"

### Check to see if Enabled/Disabled
if var_false $ENABLE_NGINX ; then
  print_notice "Disabling nginx"
  service_stop 09-nginx
  liftoff
  exit 0
fi

### Adjust NGINX Runtime Variables
UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf

mkdir -p /www/logs/nginx
chown -R nginx /www/logs/nginx
mkdir -p /tmp/nginx
chown -R nginx /tmp/nginx

liftoff
