#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service 10-openldap
PROCESS_NAME="openldap"

create_data_directories
configure_ldap_server
configure_ldap_client
configure_backup
configure_networking
configure_ppolicy_check_modules

liftoff
