#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="openldap"
check_container_initialized
check_service_initialized init
ULIMIT_N=${ULIMIT_N:-1024}
ulimit -n ${ULIMIT_N}
liftoff

### OpenLDAP
print_info "Starting OpenLDAP ${OPENDAP_VERSION}"
/usr/sbin/slapd -h "ldap://$HOSTNAME ldaps://$HOSTNAME ldapi:///" -u ldap -g ldap -d $LOG_LEVEL
