#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="openldap"
check_initialized
ULIMIT_N=${ULIMIT_N:-1024}
ulimit -n ${ULIMIT_N}

liftoff


### OpenLDAP
print_info "Starting OpenLDAP ${OPENDAP_VERSION}"
/usr/sbin/slapd -h "ldap://$HOSTNAME ldaps://$HOSTNAME ldapi:///" -u ldap -g ldap -d $LOG_LEVEL
