#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single

PROCESS_NAME="openldap"
check_container_initialized
check_service_initialized init
ulimit -n ${ULIMIT_N}
liftoff

### OpenLDAP
print_info "Starting OpenLDAP ${OPENLDAP_VERSION}"
/usr/sbin/slapd $SLAPD_ARGS -h "$SLAPD_HOSTS" -u ldap -g ldap -d $LOG_LEVEL
